### ISSUE TITLE
Need Missing Node Type References

### ISSUE THREAD

**Issue by Btazbt** [jangevaare/node-red-brew2#1]
Looks like a good example for what I'm setting out to do, but when I tried importing the json file I get the following error
>    Flows stopped due to missing node types.
> widgetlords-analog-in
> sensor-ds18b20

Can you provide links where you got these nodes?

**Comment by jangevaare** [comment]
Thanks. `package.json` wasn't committed to the repo, which conveys these dependencies. This has been added to a v0.3.1 release. Kinda important.

You can also add these dependencies through Node-RED's palette manager.

<img width="435" alt="Screen Shot 2019-11-29 at 8 28 04 AM" src="https://user-images.githubusercontent.com/5422422/69873223-be3f6f00-1285-11ea-9ab7-9ed106a14e54.png">
<img width="713" alt="Screen Shot 2019-11-29 at 8 28 57 AM" src="https://user-images.githubusercontent.com/5422422/69873224-be3f6f00-1285-11ea-8b93-42495822ef5e.png">

**Comment by Btazbt** [comment]
thanks!
